### PR TITLE
Html export fix

### PR DESCRIPTION
**Pull request by ilmartyrk**
FIX for https://github.com/ether/ep_headings2/issues/7

### CODE REVIEW

**Comment by JohnMcLear** [comment]
just check for javascript injection attacks here IE ``"><script='alrert("foo")'>`` in content

**Comment by ilmartyrk** [comment]
@JohnMcLear what should be the behaviour if injection exists?

**Comment by JohnMcLear** [comment]
``Security.HTMLEscape`` prolly

**Comment by ilmartyrk** [comment]
It will also escape any html added by other plugins eg. `ep_font_color`

**Comment by JohnMcLear** [comment]
> It will also escape any html added by other plugins eg. `ep_font_color`

Very true ;(  

Okay never mind 👍 we should be good with this as is then?

**Pull request merged**
