### PR TITLE
Fix line height

### PR DESCRIPTION
**Pull request by rhansen**
Also revert and re-do the commits from pull request #22 to preserve UNIX-style line endings and to make it easier to revert some of the changes in future pull requests.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
@seballot

**Comment by seballot** [comment]
Hi @rhansen ! I do not understand "preserve UNIX-style line endings", but if you happy with that I don't mind !

But re line-height, did you test the plugin along with etherpad develop branch? line-height is now defined in the different skins so it's easier to customize

**Comment by rhansen** [comment]
> I do not understand "preserve UNIX-style line endings"

Windows uses CR+LF for newlines, Unix-like operating systems (e.g., Linux, macOS) use just LF. Your editor must have automatically converted the line endings in the files you edited to CR+LF.

> did you test the plugin along with etherpad develop branch?

No, I didn't—I tested it on my production Etherpad instance (currently v1.7.5).

> line-height is now defined in the different skins so it's easier to customize

Are skins supposed to specify an absolute or relative height? If absolute, we would still need to specify line-height here, no?

**Comment by seballot** [comment]
Thanks for explanations :)

>  If absolute, we would still need to specify line-height here, no?

No, I don't see why?

**Comment by rhansen** [comment]
Here is the current situation (for Etherpad 1.7.5 anyway), which uses a fixed line height (`line-height: 16px`):

screenshot

Notice the overcrowding. If the Etherpad develop branch also uses a fixed line height then it will have the same problem.

**Comment by seballot** [comment]
With develop branch

image

**Comment by JohnMcLear** [comment]
@rhansen 1.8 does include some breaking changes and so an *Etherpad upgrade is necessary* as we're modernizing plugins :)  Tnx!

I appreciate this sucks but we need to move the projects forward so we're going to be dragging some admins screaming and kicking into the world of 1.8 and beyond..  We sat still for too long due to broken code.

**Comment by rhansen** [comment]
Can the plugins condition their behavior on the Etherpad version?

I can't upgrade to Etherpad 1.8.x without upgrading my i386 server (node.js 10.x dropped i386 support).

**Comment by rhansen** [comment]
I split the cleanup commits to a separate PR (#24).

**Comment by JohnMcLear** [comment]
I dropped all code for < Node 10 across all my projects a while back, sorry man!  I hate to let people down but I really think it's worth the upgrade/updates.  Please consider upgrading your hardware to support Node10+.

I know it's not a nice thing to hear but I just don't have the time to support such old tech any more, I have to move on so I don't have a spiders web of code.  We are going to be even more disruptive within Etherpad over the coming months and I expect I will be writing lots of apologies like this.

Sorry!

**Pull request closed without merging**
